### ISSUE TITLE
TypeError: sub() takes at most 4 arguments (5 given)

### ISSUE THREAD

**Issue by ptitemimidu86** [BenoitZugmeyer/addic7ed-cli#18]
Hello,

I use CentOS 6.6 and no problem for install addic7ed
But when i tried to use i got error :

--->> addic7ed once.upon.a.time.s04e21.hdtv.x264-2hd.mp4

Target SRT file: once.upon.a.time.s04e21.hdtv.x264-2hd.srt
Once Upon a Time - 04x21 - Mother
Traceback (most recent call last):
  File "/usr/bin/addic7ed", line 9, in <module>
    load_entry_point('addic7ed-cli==1.2', 'console_scripts', 'addic7ed')()
  File "/usr/lib/python2.6/site-packages/addic7ed_cli/__init__.py", line 285, in main
    globals()[namespace.command](namespace)
  File "/usr/lib/python2.6/site-packages/addic7ed_cli/__init__.py", line 140, in search
    SearchUI(arguments).launch()
  File "/usr/lib/python2.6/site-packages/addic7ed_cli/ui.py", line 135, in launch
    self.launch_file(file)
  File "/usr/lib/python2.6/site-packages/addic7ed_cli/ui.py", line 124, in launch_file
    todownload = self.episode(episode, args.language, release)
  File "/usr/lib/python2.6/site-packages/addic7ed_cli/ui.py", line 79, in episode
    episode.fetch_versions()
  File "/usr/lib/python2.6/site-packages/addic7ed_cli/episode.py", line 47, in fetch_versions
    release = re.sub('version ', '', release, 0, re.I)
TypeError: sub() takes at most 4 arguments (5 given)

Any ideas ?

**Comment by JoelSjogren** [comment]
Python 2.6 only takes 4 arguments:
> re.sub(pattern, repl, string[, count])

Try python 2.7 instead.

**Comment by ptitemimidu86** [comment]
thank you a lot
it works very well with python2.7

**Comment by BenoitZugmeyer** [comment]
Thank you for the feedback, I removed the Python 2.6 support flag to avoid future confusion!
