### ISSUE TITLE
Addic7ed crashes on Arch while searching (traceback)

### ISSUE THREAD

**Issue by f3bruary** [BenoitZugmeyer/addic7ed-cli#21]
addic7ed version 1.2

[f3bruary:/media/]$ addic7ed search Ray\ Donovan\ -\ 3x12\ -\ Exsuscito\ -\ lol.mp4                                          

Target SRT file: Ray Donovan - 3x12 - Exsuscito - lol.srt
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pyquery/pyquery.py", line 66, in fromstring
    result = getattr(etree, meth)(context)
  File "lxml.etree.pyx", line 3103, in lxml.etree.fromstring (src/lxml/lxml.etree.c:70569)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106403)
  File "parser.pxi", line 1716, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105194)
  File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:99876)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94350)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95786)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:95065)
lxml.etree.XMLSyntaxError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/addic7ed", line 9, in <module>
    load_entry_point('addic7ed-cli==1.2', 'console_scripts', 'addic7ed')()
  File "/usr/lib/python3.4/site-packages/addic7ed_cli/__init__.py", line 285, in main
    globals()[namespace.command](namespace)
  File "/usr/lib/python3.4/site-packages/addic7ed_cli/__init__.py", line 140, in search
    SearchUI(arguments).launch()
  File "/usr/lib/python3.4/site-packages/addic7ed_cli/ui.py", line 135, in launch
    self.launch_file(file)
  File "/usr/lib/python3.4/site-packages/addic7ed_cli/ui.py", line 116, in launch_file
    search_results = search(query)
  File "/usr/lib/python3.4/site-packages/addic7ed_cli/episode.py", line 101, in search
    for link in results('.tabel a')
  File "/usr/lib/python3.4/site-packages/addic7ed_cli/request.py", line 24, in __call__
    self._query = PyQuery(self.content)
  File "/usr/lib/python3.4/site-packages/pyquery/pyquery.py", line 226, in __init__
    elements = fromstring(context, self.parser)
  File "/usr/lib/python3.4/site-packages/pyquery/pyquery.py", line 70, in fromstring
    result = getattr(lxml.html, meth)(context)
  File "/usr/lib/python3.4/site-packages/lxml/html/__init__.py", line 726, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/usr/lib/python3.4/site-packages/lxml/html/__init__.py", line 614, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3103, in lxml.etree.fromstring (src/lxml/lxml.etree.c:70569)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106403)
  File "parser.pxi", line 1716, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105194)
  File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:99876)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94350)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95786)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:95065)
lxml.etree.XMLSyntaxError: None

**Comment by BenoitZugmeyer** [comment]
Thanks, I just fixed this! Please test the v1.3 and reopen it if you still have the issue.

**Comment by f3bruary** [comment]
Yep, thanks for the quick fix !
