### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by aethelz** [BenoitZugmeyer/addic7ed-cli#22]
Traceback (most recent call last):
  File "/usr/bin/addic7ed", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'addic7ed-cli==1.3' distribution was not found and is required by the application

**Comment by BenoitZugmeyer** [comment]
How did you install it?

**Comment by aethelz** [comment]
Yaourt, The usual way? Had it since time immemorial, in fact it worked after upgrade to 1.3-1. But apparently some recent update broke it I think

pacman -Qii addic7ed-cli 
Name           : addic7ed-cli
Version        : 1.3-1
Description    : Addic7ed command-line interface
Architecture   : any
URL            : https://github.com/BenoitZugmeyer/addic7ed-cli
Licenses       : Expat
Groups         : None
Provides       : None
Depends On     : python  python-pyquery  python-requests  python-setuptools
Optional Deps  : None
Required By    : None
Optional For   : None
Conflicts With : None
Replaces       : None
Installed Size :  82.00 KiB
Packager       : Unknown Packager
Build Date     : Mon 28 Sep 2015 10:31:30 PM MSK
Install Date   : Mon 28 Sep 2015 10:31:35 PM MSK
Install Reason : Explicitly installed
Install Script : No
Validated By   : None
Backup Files:
(none)

**Comment by BenoitZugmeyer** [comment]
Thanks, I found what went wrong. ArchLinux recently updated python to 3.5, and all packages previously in `/usr/lib/python3.4/site-packages` needs to be reinstalled to be in `/usr/lib/python3.5/site-packages`. Apparently, the right way to handle those change is to increment the `pkgrel` version. Let's do it.

**Comment by f3bruary** [comment]
I almost created an issue for this yesterday but a simple reinstall fixed it.
