### ISSUE TITLE
Crash when the upstream episode title contains Unicode characters

### ISSUE THREAD

**Issue by Pascal666** [BenoitZugmeyer/addic7ed-cli#33]
Addic7ed does not encode its href attributes. When an episode contains an Unicode character like "I’ve Seen the Other Side of You", the link contains the title and addic7ed-cli crashes with the exception:

`UnicodeEncodeError: 'charmap' codec can't encode character '\u2019' in position 28: character maps to <undefined>`

To reproduce: try to search and download the subtitles for the episode Dark.Matter.S02E03.mkv

May be related to #3

**Comment by Pascal666** [comment]
Dark.Matter.S02E13.mkv yields similar error:

`UnicodeEncodeError: 'charmap' codec can't encode characters in position 19-25: character maps to <undefined>`

**Comment by BenoitZugmeyer** [comment]
Thank you for the report, but I can't reproduce, I successfully download both episodes subtitles. Which OS are you using? Python 2 or 3? Which language?

**Comment by Pascal666** [comment]
Python 3.5.1 on Windows 7.

```
  Traceback (most recent call last):
  File "c:\users\pascal\appdata\local\programs\python\python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\pascal\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Pascal\AppData\Local\Programs\Python\Python35-32\Scripts\addic7ed.exe\__main__.py", line 9, in <module>
  File "c:\users\pascal\appdata\local\programs\python\python35-32\lib\site-packages\addic7ed_cli\__init__.py", line 317, in main
    globals()[namespace.command](namespace)
  File "c:\users\pascal\appdata\local\programs\python\python35-32\lib\site-packages\addic7ed_cli\__init__.py", line 142, in search
    SearchUI(arguments).launch()
  File "c:\users\pascal\appdata\local\programs\python\python35-32\lib\site-packages\addic7ed_cli\ui.py", line 178, in launch
    for (version, output_file) in self.iter_files():
  File "c:\users\pascal\appdata\local\programs\python\python35-32\lib\site-packages\addic7ed_cli\ui.py", line 153, in iter_files
    version = self.launch_file(file_arg)
  File "c:\users\pascal\appdata\local\programs\python\python35-32\lib\site-packages\addic7ed_cli\ui.py", line 142, in launch_file
    return episode and self.episode(episode, args.language, release)
  File "c:\users\pascal\appdata\local\programs\python\python35-32\lib\site-packages\addic7ed_cli\ui.py", line 97, in episode
    return self.select(versions)
  File "c:\users\pascal\appdata\local\programs\python\python35-32\lib\site-packages\addic7ed_cli\ui.py", line 36, in select
    echo(" {} : {}".format(str(index).rjust(just), choice))
  File "c:\users\pascal\appdata\local\programs\python\python35-32\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]```

**Comment by Pascal666** [comment]
Similar errors on Python 3.4.5 on CentOS 7.  From a fresh minimal CentOS 7 install:

```
#yum install epel-release
<snip>
#yum install python34-pip
<snip>
#pip3 install https://github.com/BenoitZugmeyer/addic7ed-cli/archive/master.zip
<snip>
# addic7ed Dark.Matter.S02E03.mkv
Target SRT file: Dark.Matter.S02E03.srt
Traceback (most recent call last):
  File "/usr/bin/addic7ed", line 9, in <module>
    load_entry_point('addic7ed-cli==1.4.1', 'console_scripts', 'addic7ed')()
  File "/usr/lib/python3.4/site-packages/addic7ed_cli/__init__.py", line 319, in main
    globals()[namespace.command](namespace)
  File "/usr/lib/python3.4/site-packages/addic7ed_cli/__init__.py", line 142, in search
    SearchUI(arguments).launch()
  File "/usr/lib/python3.4/site-packages/addic7ed_cli/ui.py", line 178, in launch
    for (version, output_file) in self.iter_files():
  File "/usr/lib/python3.4/site-packages/addic7ed_cli/ui.py", line 153, in iter_files
    version = self.launch_file(file_arg)
  File "/usr/lib/python3.4/site-packages/addic7ed_cli/ui.py", line 140, in launch_file
    episode = self.select(search_results)
  File "/usr/lib/python3.4/site-packages/addic7ed_cli/ui.py", line 36, in select
    echo(" {} : {}".format(str(index).rjust(just), choice))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 28: ordinal not in range(128)
# addic7ed Dark.Matter.S02E13.FUM.mkv
Target SRT file: Dark.Matter.S02E13.FUM.srt
 1 : Dark Matter - 02x13 - But First, We Save the Galaxy
 2 : Dark Matters: Twisted But True - 02x13 - Magical Jet Propulsion, Missing Link Mystery, Typhoid Mary
 S : Skip
[1] > 1
Dark Matter - 02x13 - But First, We Save the Galaxy
Traceback (most recent call last):
  File "/usr/bin/addic7ed", line 9, in <module>
    load_entry_point('addic7ed-cli==1.4.1', 'console_scripts', 'addic7ed')()
  File "/usr/lib/python3.4/site-packages/addic7ed_cli/__init__.py", line 319, in main
    globals()[namespace.command](namespace)
  File "/usr/lib/python3.4/site-packages/addic7ed_cli/__init__.py", line 142, in search
    SearchUI(arguments).launch()
  File "/usr/lib/python3.4/site-packages/addic7ed_cli/ui.py", line 178, in launch
    for (version, output_file) in self.iter_files():
  File "/usr/lib/python3.4/site-packages/addic7ed_cli/ui.py", line 153, in iter_files
    version = self.launch_file(file_arg)
  File "/usr/lib/python3.4/site-packages/addic7ed_cli/ui.py", line 142, in launch_file
    return episode and self.episode(episode, args.language, release)
  File "/usr/lib/python3.4/site-packages/addic7ed_cli/ui.py", line 97, in episode
    return self.select(versions)
  File "/usr/lib/python3.4/site-packages/addic7ed_cli/ui.py", line 69, in select
    echo(result)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-20: ordinal not in range(128)```

**Comment by BenoitZugmeyer** [comment]
Thank you very much, I did reproduce on CentOS! This is likely to be related to your locale configuration. If running `LC_ALL=en_US.UTF-8 addic7ed Dark.Matter.S02E03.mkv` works for you, you should try to configure your locales properly.

I tried to mitigate the issue by replacing problematic characters with `?` in my last commit. Let me know if it fixes the issue for you.

**Comment by Pascal666** [comment]
I can confirm prefixing with `LC_ALL=en_US.UTF-8` on CentOS eliminates the problem.

Upgrading to latest development version and attempting without the above now yields the error `AttributeError: 'Episode' object has no attribute 'encode'`

**Comment by BenoitZugmeyer** [comment]
Silly me! should be better now.

**Comment by Pascal666** [comment]
Thank you.  I can confirm that does appear to fix the crashes on both CentOS and Windows.
