### ISSUE TITLE
IndexError: list index out of range (v1.43)

### ISSUE THREAD

**Issue by timothymowens** [BenoitZugmeyer/addic7ed-cli#37]
I just upgraded to v1.43 and tested.  I'm getting the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/addic7ed", line 9, in <module>
    load_entry_point('addic7ed-cli==1.4.3', 'console_scripts', 'addic7ed')()
  File "/usr/local/lib/python2.7/dist-packages/addic7ed_cli/__init__.py", line 319, in main
    globals()[namespace.command](namespace)
  File "/usr/local/lib/python2.7/dist-packages/addic7ed_cli/__init__.py", line 142, in search
    SearchUI(arguments).launch()
  File "/usr/local/lib/python2.7/dist-packages/addic7ed_cli/ui.py", line 172, in launch
    files = list(self.iter_files())
  File "/usr/local/lib/python2.7/dist-packages/addic7ed_cli/ui.py", line 152, in iter_files
    version = self.launch_file(file_arg)
  File "/usr/local/lib/python2.7/dist-packages/addic7ed_cli/ui.py", line 141, in launch_file
    return episode and self.episode(episode, args.language, release)
  File "/usr/local/lib/python2.7/dist-packages/addic7ed_cli/ui.py", line 94, in episode
    episode.fetch_versions()
  File "/usr/local/lib/python2.7/dist-packages/addic7ed_cli/episode.py", line 68, in fetch_versions
    badsub = tr('a[href*="badsub"]')[0].attrib['href']
IndexError: list index out of range
```

Command I ran: `addic7ed Brooklyn-Nine-Nine.S05E13.720p.HDTV.x264-AVS.mkv`

OS: Ubuntu 16.04.04
Python version: 2.7
addic7ed-cli version: 1.43

**Comment by timothymowens** [comment]
Update: It worked after I re-ran: `addic7ed-cli login` and provided my credentials.  However, if the session is bad or there is no session, I was getting the 'list index out of range' error.

**Comment by BenoitZugmeyer** [comment]
Yeah sorry! fixed and released.
